language: python
python:
  - "3.6"
before_install:
  - pip install pycodestyle codecov
  - pip install -r requirements.txt
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - coverage run --parallel-mode --branch --source=. -m pytest
  - cp add_parser.py.sample add_parser.py
  - coverage run --parallel-mode --branch --source=. -m pytest
  - coverage combine
  - coverage report -m
after_success:
  - codecov
